[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.4",
    "pydantic-ai>=0.2.6",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
